rules: libprologin2013.so
map: ./map1.map
verbose: 0
clients:
  - ./champion.so
  - ./champion.so
#  - /home/cosmo/Documents/prologin/stechec2/games/prologin2013/player_env/caml/island_quest-master/final/champion.so
names:
  - Blue ones
  - Red ones
spectators:
#  - /home/cosmo/Documents/prologin/stechec2/games/prologin2013/dumper/champion.so
   - /home/cosmo/Documents/prologin/stechec2/games/prologin2013/gui/champion.so
